apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-4
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "test2.lb.com"
    service.beta.kubernetes.io/do-loadbalancer-http2-ports: "808k"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9876
