apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dokswebhooks-serving-cert
  namespace: default
spec:
  secretName: dokswebhooks-server-cert
  dnsNames:
    - dokswebhooks-service
    - dokswebhooks-service.default.svc
    # Additional DNS names will be added by C3.
  issuerRef:
    kind: ClusterIssuer
    name: cert-selfsigned-issuer
    group: cert-manager.io