---
kind: Service
apiVersion: v1
metadata:
  name: https-with-cert-minimal
  annotations:
    # No TLS port annotation needed since 443 is assumed for HTTPS when another TLS option annotation is given.
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "certificate-abc-123"
spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
