---
kind: Service
apiVersion: v1
metadata:
  name: https-with-cert-minimal
  annotations:
    # Certificate ID and A records will automatically be generated for this domain
    service.beta.kubernetes.io/do-loadbalancer-domain: "sample.digitalocean.com"
spec:
  type: LoadBalancer
  selector:
    app: nginx-example
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
