name: release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'tag and release to create'
        # Input has to be provided for the workflow to run
        required: true
env:
  GITHUB_ENV: ".env"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: run make bump-version
        run: make bump-version
        env:
          NEW_VERSION: ${{ github.event.inputs.tag }}
      - name: commit manifests
        uses: EndBug/add-and-commit@a988073222b8bd50f3ecfca9c0ab7dfbf0d08ceb
        with:
          message: "create release manifests for ${{ github.event.inputs.tag }}"
          add: "releases/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # target commit should be the commit with the new release manifest, not the commit when workflow was triggered
      - name: find target commit to tag
        run: |
          sha=$(git rev-parse HEAD)
          echo "TARGET_SHA=$sha" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: actions/create-release@1e92f6fc665e271a5435631ba00711fdd83d9d27
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitish: ${{ env.TARGET_SHA }}
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}
      - name: Publish Docker Image
        run: make publish
