name: release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'tag and release to create'
        # Input has to be provided for the workflow to run
        required: true
env:
  GITHUB_ENV: ".env"
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          ref: master

      - name: Install go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Install cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2

      - name: Install crane
        uses: uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3

      - name: Login to dockerhub to push the image
        run: echo "${{ secrets.DockerHubToken }}" | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DockerHubUser }}

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubToken }}

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker Image
        env:
          VERSION: ${{ github.event.inputs.tag }}
        run: make ci publish

      - name: Sign Image and copy to ghcr.io
        env:
          VERSION: ${{ github.event.inputs.tag }}
        run: make sign copy-ghcr

      - name: run make bump-version
        run: make bump-version
        env:
          NEW_VERSION: ${{ github.event.inputs.tag }}

      - name: commit manifests
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9.1.3
        with:
          message: "create release manifests for ${{ github.event.inputs.tag }}"
          add: "releases/ VERSION CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # target commit should be the commit with the new release manifest, not the commit when workflow was triggered
      - name: find target commit to tag
        run: |
          sha=$(git rev-parse HEAD)
          echo "TARGET_SHA=$sha" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ env.TARGET_SHA }}
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          body: See the [CHANGELOG](https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/${{ github.event.inputs.tag }}/CHANGELOG.md) for details.
