name: ci
on:
  pull_request:
  push:
    branches: [ master ]
env:
  GOFLAGS: "-mod=vendor"
  GITHUB_ENV: ".env"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 1

      - name: Install go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Run tests
        run: make ci

      - name: Verify container image build
        run: make build

  release-dev-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 1

      - name: Install go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ secrets.DockerHubUser }}
          password: ${{ secrets.DockerHubToken }}

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push new CCM dev image
        run: |
          VERSION=dev make publish sign copy-ghcr
