name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GOFLAGS: "-mod=vendor"
  GITHUB_ENV: ".env"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f
        with:
          go-version: ^1.15
      - name: Check out code into the Go module directory
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: install golint
        run: go install -mod=vendor golang.org/x/lint/golint
      - name: Run test command
        run: make ci
