name: ci
on:
  pull_request:
  push:
    branches: [ master ]
env:
  GOFLAGS: "-mod=vendor"
  GITHUB_ENV: ".env"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@0caeaed6fd66a828038c2da3c0f662a42862658f
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Verify docker image builds
        run: make build

      - name: Run test command
        run: make ci
